### ISSUE TITLE
我来抛砖引玉提几个小意见

### ISSUE THREAD

**Issue by qiulang** [NoderSurvey/reporters#1]
首先感谢有这么一份调查，辛苦了！如果以后能慢慢做出像 https://github.com/kamranahmedse/developer-roadmap 就完美了 

我来抛砖引玉提几个小意见：

1. **关于应用场景**，SO 有一个讨论 [How to decide when to use Node.js?](https://stackoverflow.com/questions/5062614/how-to-decide-when-to-use-node-js) 我觉得很好，可以借鉴下。 比如，我觉得websocket是nodejs一大使用场景，但目前调查没有涉及。另外，现在SPA这么流行，感觉 nodejs 做REST api 服务器或许不少，关于REST api 服务器的话题或许可以单独拿出来讨论。

2. **关于学习途径**，学习中碰到的坑，可以多深入一点，比如市面上都有什么样的书值得看看。同样在SO也有类似问题, [How do I get started with Node.js]( https://stackoverflow.com/questions/2353818/how-do-i-get-started-with-node-js)

3. **关于教训**，我个人最大教训是从17开始我在我们公司”鼓吹“nodejs，想大力推广，一大原因就是受了”全栈“诱惑，觉得写前端的人也可以做后端了。可是这些年实践下来可耻的失败了。虽然都是js开发，前端需要的skill set和后端还是很大不同，真的很难有又能做前端又能做后端，还做得好的（牛逼的人就不算了）。我记得我看过netflix 类似讨论，结论好像也是太难了 （好像是在这个视频里 Nodejs at Netflix https://www.youtube.com/watch?v=p74282nDMX8 ) 。 **全栈工程师话题**可以单独拿来讨论。
 
4. **关于开发难点**（可以算在”使用困惑"里），我个人觉得一个大问题是npm包太多了，如何选择一个合适的包有很多考虑，这个工作需要一定经验，入行不久的人可能做不好。。比如发http请求除了axios，其实还有三四个流行包；关于记log包也有很多选择，到底用哪个合适？
 
5. **几个技术小问题**  
    a. 关于配置，为什么要把环境变量和文件配置分开来？dotenv这个包我感觉做项目是必不可少啊。[12factor](https://12factor.net/zh_cn/config)也是这么说的（我个人理解）
    b. 关于进程管理，我自己是在docker还用了pm2，我觉得不一定要分开. 
    c. 单线程模式, worker thread ，有线程开发经验的人，刚接触到nodejs单线程模式可能都会打个问号（我也是）所以或者值得讨论下，延伸的讨论可能就还会涉及到pm2
    d.关于web框架，我也琢磨一段koa，但真的感觉太小众，实际项目用到多少我有点。。。TJ 自己在quora也回答了类似问题 https://www.quora.com/Why-hasnt-Koa-been-as-popular-as-Express
   e. 关于nodejs和nginx一起用, SO 这个讨论[Node.js + Nginx - What now?](https://stackoverflow.com/questions/5009324/node-js-nginx-what-now)

先提这么多，有想到再补充

邱朗

**Comment by Lellansin** [comment]
WebSocket 确实没有收录到问卷的问题里，这个后续可以加入到问题列表（问卷的问题后续也会考虑整理成 GItHub 仓库接受大家的建议和 PR）。REST API 是严格意义上的一个服务端 API 的子集，不像 SSR 或者 Websocket 这样跟服务端 API 有这个明确的区别，所以是否单独列出来还需要商榷。

NPM 包太多了不知道如何选择这个可能考虑修改 “node_modules 依赖” 的描述，可能改成 “NPM 依赖” 或者 “依赖扩展” 应该就可以包括。

即使可以通过 dotenv 来配置文件配置到环境变量，也是要注意环境变量与文件配置是分开的两个概念。同时这个问题与你提到的 docker 和 pm2 分开一样，这些问题的选项都是多选的，是可以互相包含而不是互斥的。

**Comment by qiulang** [comment]
> 这些问题的选项都是多选的，是可以互相包含而不是互斥的。

我就是这个意思，因为从报告图表看，至少给我感觉他们被列为互斥。

我另外还想补充一个，就是哪些npm包在开发中必不可少。比如 lodash, moment,  debug, nodemon, pm2 ...

**Comment by JianmingXia** [comment]
说实话 Koa 占比这么低我是有点意外的= =，忘记当时统计的时候，有没有列出“线上项目”这个前提

**Comment by Lellansin** [comment]
> 我另外还想补充一个，就是哪些npm包在开发中必不可少。比如 lodash, moment, debug, nodemon, pm2 ...

@qiulang  这个部分按照目前问卷的问题设计，主要是统一归属于 “最佳实践” 的资料缺乏这个问题上。

另外，单纯的统计哪个 NPM 必不可少可能存在很大的局限，效果估计类似 npmjs.com 首页上的 Popular libraries。

而要按照某个具体的 keyword 来统计的话，那么效果可能类似 npm 自带搜索的侧边栏上 Pupularity、Quality、Maintenance 三个筛选的情况，这个筛选可能比用户填写问卷反馈的准确性和维度都要好上一些。

二者之间的情况要展开的话，单独开一份问卷都是可能的，综合权衡下来还是某个领域的最佳实践比较靠谱。比如 egg 作为一个解决方案，它本身就集成了 koajs、chalk、debug、iconv-lite、moment 、pillarjs/cookies、visionmedia/supertest 等等一系列依赖。

所以按照这个思路如果你不喜欢 egg，喜欢 Nest.js，那么你找到 Nest.js 官方提供的例子，在 npm isntall 之后通过 npm list 的方式把它背后的具体依赖打印出来，那么其中列出来的 npm 依赖本身就是 Nest.js 这个方案所推荐的了。

如果在这些成熟的框架里找不到你要的 npm，是不是可以思考一下我们需要的 npm 是不是在某些特别场景下的。进一步说，这个时候我们是不是更应该关注的时候这些特定的场景以及这些场景下的最佳实践。

个人看法是单纯的看某个 npm 的流行程度/下载量/使用频率，其实是脱离了场景的，因为这时候我们其实已经在心里暗示了自己 “这个 npm 是一个银弹“。然而现实情况是我们都知道不可能存在银弹。

**Comment by qiulang** [comment]
@Lellansin 你说的有道理 ，统计npm包确实要分类，像 https://2019.stateofjs.com/zh/ 这样。

所以 “哪些npm包在开发中**必不可少**” 改成““哪些npm包**你需要知道**”更有意义 ，比如做前端开发，chalk 不是必不可少 （虽然它在npm上流行度很高）；做后端开发开发也不需要 browserify，但是知道有他们对了解整个npm生态系统会很有帮助。

另外，单单从npmjs.com 的流行度去找包其实有些问题。比如 request这个包如果从 npmjs流行度排行是很高的，但应该知道他的作者已经放弃了，不再更新，所以新的项目就尽量不要再用了。要找npm包有时从 https://github.com/sindresorhus/awesome-nodejs 更方便，因为它已经做了归类。

**Comment by lushi118** [comment]
原先我做后端架构，刚刚转前端，负责前端工程化，从我来看更想了解：1)大厂【AT】再前端工程化、前后端职责划分等方面是怎么做的？2)尤其是node与java【如果是阿里的话】之间角色如何分配？node和java比在生态上还是很大差距，node做后端开发【+db/nosql，输出rest-api】感觉还是不太合适；3)graphql(apollo)对node的有利影响以及gql在AT中如何应用？从我来看gql比较适合放在node+bff这层，node+gql+apollo比较适合做一些内网站点，尤其是一些逻辑相对简单的后台管理系统。

**Comment by Lellansin** [comment]
> 所以 “哪些npm包在开发中**必不可少**” 改成““哪些npm包**你需要知道**”更有意义 ，比如做前端开发，chalk 不是必不可少 （虽然它在npm上流行度很高）；做后端开发开发也不需要 browserify，但是知道有他们对了解整个npm生态系统会很有帮助。

这个就是场景了，需要了解的是某一个场景的最佳实践 or 推荐实践。

> 另外，单单从npmjs.com 的流行度去找包其实有些问题。比如 request这个包如果从 npmjs流行度排行是很高的，但应该知道他的作者已经放弃了，不再更新，所以新的项目就尽量不要再用了。要找npm包有时从 https://github.com/sindresorhus/awesome-nodejs 更方便，因为它已经做了归类。

request 在废弃之后 npm 上就搜不到了（npm 官网其实挺好用的，不过没有 PHP 社区那种评论的功能，可能少了一点感情🤔），通过 npm 安装 request 的时候也会有 deprecated 提示（似乎不少人安装的时候从来不看英文提示？）。

反复提了几次，更推荐的方式是从实践和场景的角度去找包，比如通过 https://github.com/goldbergyoni/nodebestpractices 来找自己要做的事情然后再去找依赖包。更重要的事情是知道自己要什么，而不是看到什么好就用什么。


> 1)大厂【AT】再前端工程化、前后端职责划分等方面是怎么做的？2)尤其是node与java【如果是阿里的话】之间角色如何分配？node和java比在生态上还是很大差距，node做后端开发【+db/nosql，输出rest-api】感觉还是不太合适；3)graphql(apollo)对node的有利影响以及gql在AT中如何应用？从我来看gql比较适合放在node+bff这层，node+gql+apollo比较适合做一些内网站点，尤其是一些逻辑相对简单的后台管理系统。

这个问卷 & 报告分析是针对社区开发者的，没有单独针对大厂的场景问题（大厂的很多问题在中小公司可能没什么借鉴意义）。建议可以抽象一下能够具体到问卷的问题，后面会把问卷也整理上来，你关心的问题如果没有选项的话，是没法数据化统计的。

**Comment by Lellansin** [comment]
这个 thread 没有更具体的问题的话暂时先 close。如果有别的问题欢迎开个新的 issue 来讨论。（当前 issue 也欢迎继续讨论）
